/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.resident;

import Business.EcoSystem;
import Business.MessageNotification.ResidentRelatedMessage;
import Business.Role.ResidentRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author luoyu
 */
public class CreateVitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateVitalJPanel
     */
    JPanel cardSequenceJPanel;
    EcoSystem ecoSystem;
    UserAccount userAccount;
    public CreateVitalJPanel(JPanel cardSequenceJPanel, EcoSystem ecoSystem, UserAccount userAccount) {
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.ecoSystem = ecoSystem;
        this.userAccount = userAccount;
        System.out.println(((ResidentRole)userAccount.getRole()).getDisease());
        initComponents();
        updateJTextField.setText(((ResidentRole)userAccount.getRole()).getDisease());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempJLabel = new javax.swing.JLabel();
        bloodJLabel = new javax.swing.JLabel();
        pulseJLabel = new javax.swing.JLabel();
        temTxt = new javax.swing.JTextField();
        bloodTxt = new javax.swing.JTextField();
        pulsetxt = new javax.swing.JTextField();
        uploadJBtn = new javax.swing.JButton();
        backJBtn = new javax.swing.JButton();
        confirmJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        updateJTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 204, 255));

        tempJLabel.setText("Tempreture:");

        bloodJLabel.setText("Blood Pressure:");

        pulseJLabel.setText("Pulse:");

        uploadJBtn.setText("Upload");
        uploadJBtn.setEnabled(false);
        uploadJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadJBtnActionPerformed(evt);
            }
        });

        backJBtn.setText("<<Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });

        confirmJButton.setText("Confirm");
        confirmJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("degree centigrade");

        jLabel2.setText("times/min");

        jLabel3.setText("mmHG");

        jButton1.setText("Update Disease:");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        updateJTextField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tempJLabel)
                            .addComponent(bloodJLabel)
                            .addComponent(pulseJLabel))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bloodTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(temTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pulsetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confirmJButton)
                                    .addComponent(uploadJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempJLabel)
                    .addComponent(temTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodJLabel)
                    .addComponent(bloodTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pulseJLabel)
                    .addComponent(pulsetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(updateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(confirmJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uploadJBtn)
                .addGap(18, 18, 18)
                .addComponent(backJBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        //refresh table
        Component[] componentArray = cardSequenceJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ResidentMainJPanel residentMainJPanel = (ResidentMainJPanel) component;
        residentMainJPanel.populateVitalSignTable();
        
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        layout.previous(cardSequenceJPanel);
        
        
        
    }//GEN-LAST:event_backJBtnActionPerformed

    private void confirmJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmJButtonActionPerformed
        // TODO add your handling code here:
        bloodTxt.setEnabled(false);
        pulsetxt.setEnabled(false);
        temTxt.setEnabled(false);
        uploadJBtn.setEnabled(true);
        confirmJButton.setEnabled(false);
        updateJTextField.setEnabled(false);
    }//GEN-LAST:event_confirmJButtonActionPerformed

    private void uploadJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadJBtnActionPerformed
        // TODO add your handling code here:
        boolean rightType = true;
        try {
            Double.parseDouble(temTxt.getText());
            Double.parseDouble(bloodTxt.getText());
            Double.parseDouble(pulsetxt.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Only numbers allowed in above 4 blanks.");
            rightType = false;
        }
        
        if(rightType){
            ResidentRelatedMessage residentVitalSign = new ResidentRelatedMessage();
            residentVitalSign.setSender(userAccount);
            residentVitalSign.setBloodPressure(bloodTxt.getText()+" mmHG");
            residentVitalSign.setPulse(pulsetxt.getText()+" times/min");
            residentVitalSign.setTemperature(temTxt.getText()+" degree centigrade");
            residentVitalSign.setPostDate(new Date());
            ((ResidentRole)userAccount.getRole()).setDisease(updateJTextField.getText());

            userAccount.getMessageQueue().getMessages().add(residentVitalSign);
            JOptionPane.showMessageDialog(null, "Created successfully.");
        }
        
        
        bloodTxt.setEnabled(true);
        pulsetxt.setEnabled(true);
        temTxt.setEnabled(true);
        confirmJButton.setEnabled(true);
        uploadJBtn.setEnabled(false);
        
        bloodTxt.setText("");
        pulsetxt.setText("");
        temTxt.setText("");
        
        temTxt.requestFocusInWindow();
    }//GEN-LAST:event_uploadJBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        updateJTextField.setEnabled(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJBtn;
    private javax.swing.JLabel bloodJLabel;
    private javax.swing.JTextField bloodTxt;
    private javax.swing.JButton confirmJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel pulseJLabel;
    private javax.swing.JTextField pulsetxt;
    private javax.swing.JTextField temTxt;
    private javax.swing.JLabel tempJLabel;
    private javax.swing.JTextField updateJTextField;
    private javax.swing.JButton uploadJBtn;
    // End of variables declaration//GEN-END:variables
}
