/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.EPAOfficial;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.MessageNotification.NeedConfirmMessage;
import Business.MessageNotification.PostMessage;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhengwenkai
 */
public class EPAOfficialMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EPAOfficialMainJPanel
     */
    
    JPanel cardSequenceJPanel;
    EcoSystem ecoSystem;
    Enterprise enterprise;
    Organization organization;
    UserAccount userAccount;
    UserAccount communityOfficialAccount;
    public EPAOfficialMainJPanel(JPanel cardSequenceJPanel, EcoSystem ecoSystem, Enterprise enterprise, Organization organization, UserAccount userAccount) {
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.ecoSystem = ecoSystem;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = userAccount;
        initComponents();
        valueLabel.setText(userAccount.getArea());
        populateMessageTable();
        populateReportTable();
    }
    

    public void populateReportTable(){
        DefaultTableModel model = (DefaultTableModel) reportJTable.getModel();
        model.setRowCount(0);
        for(Network n : ecoSystem.getNetworkList()){
            //在同一城市
            if(n.getName().equals(enterprise.getUserAccountDirectory().getUserAccountList().get(0).getArea())){
                for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                    //是社区类型
                    if(e.getEnterpriseType() == Enterprise.EnterpriseType.Community){
                        //在同一个地区，因为一个城市有很多地区，所以需要找到是相同地区的
                        if(e.getName().equals(userAccount.getArea())){
                            communityOfficialAccount = e.getUserAccountDirectory().getUserAccountList().get(0);
                            for(PostMessage p : communityOfficialAccount.getMessageQueue().getMessages()){
                                //接受人是这个官员
                                if(p.getReceiver() == userAccount){
                                    Object[] row = new Object[3];
                                    row[0] = communityOfficialAccount;
                                    row[1] = ((PostMessage)p).getMessage();
                                    row[2] = ((PostMessage)p).getPostDate();

                                    model.addRow(row);
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    
    public void populateMessageTable(){
        DefaultTableModel model = (DefaultTableModel) analystMessageJTable.getModel();
        model.setRowCount(0);
        for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
            //在同一个enterprise下找到EPAAnalyst类型的orga
            if(o.getOrganizationType() == Organization.Type.EPAAnalyst){
                for(PostMessage p : o.getMessageQueue().getMessages()){
                    //在EPAAnalyst的organization消息列表中找到属于自己的消息
                    if(p.getReceiver() == userAccount){
                        Object[] row = new Object[2];
                        row[0] = ((PostMessage)p).getMessage();
                        row[1] = ((PostMessage)p).getPostDate();

                        model.addRow(row);
                    }
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reportJTable = new javax.swing.JTable();
        valueLabel = new javax.swing.JLabel();
        communityJLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        analystMessageJTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sendUpdateCriteriaJButton = new javax.swing.JButton();
        sendWarnJButton = new javax.swing.JButton();
        refreshJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        reportJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Community Official", "Report Content", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reportJTable);

        valueLabel.setText("<value>");

        communityJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        communityJLabel.setText("Community :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("EPA Official Work Area");

        analystMessageJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Message Content", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(analystMessageJTable);

        jLabel14.setText("Report From Community Official: ");

        jLabel15.setText("Message From EPA Analyst: ");

        sendUpdateCriteriaJButton.setText("Send Update Criteria Request");
        sendUpdateCriteriaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendUpdateCriteriaJButtonActionPerformed(evt);
            }
        });

        sendWarnJButton.setText("Send Warn Request");
        sendWarnJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendWarnJButtonActionPerformed(evt);
            }
        });

        refreshJBtn.setText("Refresh");
        refreshJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendWarnJButton)
                    .addComponent(jLabel15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(communityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel14)
                                .addComponent(jLabel13))
                            .addGap(18, 18, 18)
                            .addComponent(refreshJBtn)))
                    .addComponent(sendUpdateCriteriaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(communityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(valueLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(sendWarnJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendUpdateCriteriaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendWarnJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendWarnJButtonActionPerformed
        // TODO add your handling code here:
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to SEND WARN REQUEST?", "Warning", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                PostMessage newMessage = new NeedConfirmMessage();
                newMessage.setMessage("Please warn all of your community residents!");
                newMessage.setPostDate(new Date());
                
                newMessage.setReceiver(communityOfficialAccount);
                newMessage.setSender(userAccount);
                
                organization.getMessageQueue().getMessages().add(newMessage);
            }
    }//GEN-LAST:event_sendWarnJButtonActionPerformed

    private void sendUpdateCriteriaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendUpdateCriteriaJButtonActionPerformed
        // TODO add your handling code here:
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to SEND UPDATE CRITERIA REQUEST?", "Warning", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                PostMessage newMessage = new NeedConfirmMessage();
                newMessage.setMessage("Please update the criteria according to the new data!");
                newMessage.setPostDate(new Date());
                UserAccount ua = null;
                for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
                    //在同一个enterprise下找到EPAAnalyst类型的orga
                    if(o.getOrganizationType() == Organization.Type.EPAAnalyst){
                        for(UserAccount u : o.getUserAccountDirectory().getUserAccountList()){
                            //在EPAAnalyst的organization中找到一个地区的
                            if(u.getArea().equals(userAccount.getArea())){
                                ua = u;
                            }
                        }
                    }
                }
                newMessage.setReceiver(ua);
                newMessage.setSender(userAccount);
                
                organization.getMessageQueue().getMessages().add(newMessage);
            }
    }//GEN-LAST:event_sendUpdateCriteriaJButtonActionPerformed

    private void refreshJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJBtnActionPerformed
        // TODO add your handling code here:
        populateMessageTable();
        populateReportTable();
    }//GEN-LAST:event_refreshJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable analystMessageJTable;
    private javax.swing.JLabel communityJLabel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshJBtn;
    private javax.swing.JTable reportJTable;
    private javax.swing.JButton sendUpdateCriteriaJButton;
    private javax.swing.JButton sendWarnJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
