/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.communityOfficial;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.MessageNotification.NeedConfirmMessage;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.SensorOrganization;
import Business.Sensor.Sensor;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author zhengwenkai
 */
public class CommunityOfficialSendReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityOfficialSendReportJPanel
     */
    JPanel cardSequenceJPanel;
    EcoSystem ecoSystem;
    Enterprise enterprise;
    UserAccount userAccount;
    Double percent;
    public CommunityOfficialSendReportJPanel(JPanel cardSequenceJPanel, EcoSystem ecoSystem, Enterprise enterprise, UserAccount userAccount, Double percent) {
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.ecoSystem = ecoSystem;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.percent = percent;
        initComponents();
        populateReport();
    }

    public void populateReport(){
        reportJTextArea.setText("Unhealthy percent: "+percent+"%");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reportJTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        backJBtn = new javax.swing.JButton();
        confirmJButton = new javax.swing.JButton();
        sendJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        reportJTextArea.setColumns(20);
        reportJTextArea.setRows(5);
        jScrollPane1.setViewportView(reportJTextArea);

        jLabel1.setText("Report Content");

        backJBtn.setText("<<Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });

        confirmJButton.setText("Confirm");
        confirmJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmJButtonActionPerformed(evt);
            }
        });

        sendJBtn.setText("Send");
        sendJBtn.setEnabled(false);
        sendJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backJBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(confirmJButton)
                                .addComponent(sendJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmJButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendJBtn)
                    .addComponent(backJBtn))
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        //refresh table
        Component[] componentArray = cardSequenceJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CommunityOfficialMainJPanel communityOfficialMainJPanel = (CommunityOfficialMainJPanel) component;

        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        layout.previous(cardSequenceJPanel);

    }//GEN-LAST:event_backJBtnActionPerformed

    private void confirmJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmJButtonActionPerformed
        // TODO add your handling code here:
        reportJTextArea.setEnabled(false);
        sendJBtn.setEnabled(true);
        confirmJButton.setEnabled(false);
    }//GEN-LAST:event_confirmJButtonActionPerformed

    private void sendJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendJBtnActionPerformed
        // TODO add your handling code here:
        NeedConfirmMessage needConfirmMessage = new NeedConfirmMessage();
        needConfirmMessage.setSender(userAccount);
        UserAccount receiverAccount = null;
        for(Network n : ecoSystem.getNetworkList()){
            //社区的管理员地区就是整个网络的地址
            if(n.getName().equals(userAccount.getArea())){
                for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                    if(e.getEnterpriseType() == Enterprise.EnterpriseType.EPA){
                        for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                            if(o.getOrganizationType() == Organization.Type.EPAOfficial){
                                for(UserAccount u : o.getUserAccountDirectory().getUserAccountList()){
                                    //社区的名字就是地区
                                    if(u.getArea().equals(enterprise.getName())){
                                        receiverAccount = u;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        needConfirmMessage.setReceiver(receiverAccount);
        needConfirmMessage.setMessage(reportJTextArea.getText());
        needConfirmMessage.setPostDate(new Date());

        userAccount.getMessageQueue().getMessages().add(needConfirmMessage);

        reportJTextArea.setEnabled(true);
        confirmJButton.setEnabled(true);
        sendJBtn.setEnabled(false);

        reportJTextArea.setText("");

        reportJTextArea.requestFocusInWindow();
    }//GEN-LAST:event_sendJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJBtn;
    private javax.swing.JButton confirmJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea reportJTextArea;
    private javax.swing.JButton sendJBtn;
    // End of variables declaration//GEN-END:variables
}
