/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.systemAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.CommunityOfficialRole;
import Business.Role.MayorRole;
import Business.Role.EPAOfficialRole;
import Business.Role.SensorManagerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhengwenkai
 */
public class ManageEnterpriseAdminsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseAdminsJPanel
     */
    JPanel rightJPanel;
    EcoSystem ecoSystem;
    public ManageEnterpriseAdminsJPanel(JPanel rightJPanel, EcoSystem ecoSystem) {
        this.rightJPanel = rightJPanel;
        this.ecoSystem = ecoSystem;
        initComponents();
        populateTable();
        populateNetworkComboBox();
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterprisesJTable.getModel();

        model.setRowCount(0);
        for (Network network : ecoSystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[4];
                    row[0] = network.getName();
                    row[1] = enterprise.getEnterpriseType().getValue();
                    row[2] = enterprise.getName();
                    row[3] = userAccount.getUserName();

                    model.addRow(row);
                }
            }
        }
    }
    
    private void populateNetworkComboBox(){
        networkJComboBox.removeAllItems();
        
        for (Network network : ecoSystem.getNetworkList()){
            networkJComboBox.addItem(network);
        }
    }
    
    private void populateEnterpriseComboBox(Network network){
        enterpriseNameJComboBox.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            enterpriseNameJComboBox.addItem(enterprise);
        }
        
    }
    
    private void populateEnterpriseAreaComBox(Network network){
        enterpriseAreaJComboBox.removeAllItems();
        enterpriseAreaJComboBox.addItem(network.getName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterprisesJTable = new javax.swing.JTable();
        networkJComboBox = new javax.swing.JComboBox();
        enterpriseNameJComboBox = new javax.swing.JComboBox();
        enterpriseNameJLabel = new javax.swing.JLabel();
        networkJLabel = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        reJPasswordField = new javax.swing.JPasswordField();
        usernameJLable = new javax.swing.JLabel();
        passwordJLable = new javax.swing.JLabel();
        rePasswordJLabel = new javax.swing.JLabel();
        createJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        enterpriseAreaJComboBox = new javax.swing.JComboBox<>();
        enterpriseAreaJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        enterprisesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network", "Enterprise Type", "Enterprise Name", "Admin's Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterprisesJTable);
        if (enterprisesJTable.getColumnModel().getColumnCount() > 0) {
            enterprisesJTable.getColumnModel().getColumn(0).setResizable(false);
            enterprisesJTable.getColumnModel().getColumn(1).setResizable(false);
            enterprisesJTable.getColumnModel().getColumn(2).setResizable(false);
            enterprisesJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });

        enterpriseNameJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        enterpriseNameJLabel.setText("Enterprise Name:");

        networkJLabel.setText("Network:");

        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyReleased(evt);
            }
        });

        reJPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reJPasswordFieldKeyReleased(evt);
            }
        });

        usernameJLable.setText("Username:");

        passwordJLable.setText("Password:");

        rePasswordJLabel.setText("Re-enter Password :");

        createJButton.setText("Create");
        createJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        enterpriseAreaJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        enterpriseAreaJLabel.setText("Enterprise Area:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(enterpriseNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(networkJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(usernameJLable)
                            .addComponent(passwordJLable)
                            .addComponent(rePasswordJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usernameTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enterpriseNameJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enterpriseAreaJLabel)
                                    .addComponent(enterpriseAreaJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createJButton))))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(networkJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(enterpriseAreaJLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseNameJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseAreaJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameJLable)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordJLable)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rePasswordJLabel)
                    .addComponent(reJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createJButton))
                .addGap(18, 18, 18)
                .addComponent(backJButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyReleased
        // TODO add your handling code here:
        //In order to compare .getPassword(), we shoule use String.valueOf() to convert password into string, toString() doesn't work.
        if(!String.valueOf(reJPasswordField.getPassword()).equals(String.valueOf(jPasswordField.getPassword()))){
            reJPasswordField.setBackground(Color.red);
        }
        else
        reJPasswordField.setBackground(Color.white);
    }//GEN-LAST:event_jPasswordFieldKeyReleased

    private void reJPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reJPasswordFieldKeyReleased
        // TODO add your handling code here:
        if(!String.valueOf(reJPasswordField.getPassword()).equals(String.valueOf(jPasswordField.getPassword()))){
            reJPasswordField.setBackground(Color.red);
            System.out.println(jPasswordField.getPassword());
        }
        else
        reJPasswordField.setBackground(Color.white);
    }//GEN-LAST:event_reJPasswordFieldKeyReleased

    private void createJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButtonActionPerformed
        // TODO add your handling code here:
        Enterprise enterprise = (Enterprise) enterpriseNameJComboBox.getSelectedItem();
        
        String username = usernameTxt.getText();
        String password = String.valueOf(jPasswordField.getPassword());
        UserAccount account = null;
        if(!enterprise.getUserAccountDirectory().checkIfUsernameIsUnique(username)){
            JOptionPane.showMessageDialog(null, "The user name has already existed.");
            return;
        }
        if(password.equals(String.valueOf(reJPasswordField.getPassword()))){
            if(enterprise.getEnterpriseType().getValue().equals("EPA")){
                //市长就是EPA的管理者，整个EPA Enterprise的头
                account = enterprise.getUserAccountDirectory().createUserAccount(username, password, new MayorRole(), enterprise.getName());
                account.setArea(String.valueOf(enterpriseAreaJComboBox.getSelectedItem()));
            }
            else if(enterprise.getEnterpriseType().getValue().equals("Community")){
                //社区官员是社区的管理者。
                account = enterprise.getUserAccountDirectory().createUserAccount(username, password, new CommunityOfficialRole(), enterprise.getName());
                account.setArea(String.valueOf(enterpriseAreaJComboBox.getSelectedItem()));
            }
            else if(enterprise.getEnterpriseType().getValue().equals("Sensor Company")){
                //传感器管理员就是公司的头。
                account = enterprise.getUserAccountDirectory().createUserAccount(username, password, new SensorManagerRole(), enterprise.getName());
                account.setArea(String.valueOf(enterpriseAreaJComboBox.getSelectedItem()));
            }
            populateTable();
        }
        else{
            JOptionPane.showMessageDialog(null, "Please enter same password.");
            return;
        }
        System.out.println(account.getArea());
    }//GEN-LAST:event_createJButtonActionPerformed

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed
        // TODO add your handling code here:
        Network network = (Network) networkJComboBox.getSelectedItem();
        if (network != null){
            populateEnterpriseComboBox(network);
            populateEnterpriseAreaComBox(network);
        }
    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        rightJPanel.remove(this);
        Component[] componentArray = rightJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminMainJPanel systemAdminMainJPanel = (SystemAdminMainJPanel) component;
        systemAdminMainJPanel.populateTree();
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.previous(rightJPanel);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createJButton;
    private javax.swing.JComboBox<String> enterpriseAreaJComboBox;
    private javax.swing.JLabel enterpriseAreaJLabel;
    private javax.swing.JComboBox enterpriseNameJComboBox;
    private javax.swing.JLabel enterpriseNameJLabel;
    private javax.swing.JTable enterprisesJTable;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JLabel networkJLabel;
    private javax.swing.JLabel passwordJLable;
    private javax.swing.JPasswordField reJPasswordField;
    private javax.swing.JLabel rePasswordJLabel;
    private javax.swing.JLabel usernameJLable;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
